### ISSUE TITLE
error " filesystem: No such file or directory  #include <filesystem>" while compiling

### ISSUE THREAD

**Issue by studiokrause** [ALLATRA-IT/srt-server#11]
Trying to compile with cmake 3.24.1 on Ubuntu 18.04.6 LTS, got this error:

root@xxxxxxx:~/tmp/srt-server# sudo make
[ 25%] Building CXX object CMakeFiles/srt-server.dir/source/core.cpp.o
In file included from /home/ubuntu/tmp/srt-server/source/core.cpp:1:0:
/home/ubuntu/tmp/srt-server/source/../headers/main.h:25:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/srt-server.dir/build.make:75: recipe for target 'CMakeFiles/srt-server.dir/source/core.cpp.o' failed
make[2]: *** [CMakeFiles/srt-server.dir/source/core.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/srt-server.dir/all' failed
make[1]: *** [CMakeFiles/srt-server.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
